// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';
import { name, version } from '../../package.json';

export const environment = {
  production: true,
  name,
  version: env.npm_package_version,

  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US'],
  // STS configuration settings
  stsConfig: {
    clientId: 'morris-test-client-localhost',
    redirectUri: window.location.origin,
    postLogoutRedirectUri: window.location.origin,
    authority: 'https://morrisgisapps.co.morris.nj.us/STS/morris-sts-dev',
    scopes:
      'email openid profile morris-developer-profile employee-profile morris_client_api morris_user_api morris_email_api morris_storage_api surveyresource_api',
    authWellknownEndpointUrl: 'https://login.microsoftonline.com/common/v2.0',
    responseType: 'code',
    silentRenew: true,
    maxIdTokenIatOffsetAllowedInSeconds: 600,
    issValidationOff: true,
    autoUserInfo: false,
    // silentRenewUrl: window.location.origin + '/silent-renew.html',
    useRefreshToken: true,
  },

  // API resources
  serverUrl: 'https://morrisgisapps.co.morris.nj.us',
  morrisClientApiUrl: 'https://morrisgisapps.co.morris.nj.us/apis/morris-clients-api',
  morrisIdentityApiUrl: 'https://morrisgisapps.co.morris.nj.us/apis/morris-identityapi',
  morrisEmailApiUrl: 'https://morrisgisapps.co.morris.nj.us/svcs/mail',
  morrisStorageApiUrl: 'https://morrisgisapps.co.morris.nj.us/svcs/az-storage',
  surveyResourcesApiUrl: 'https://morrisgisapps.co.morris.nj.us/apis/survey-resources',
  spatialapiUrl: 'https://morrisgisapps.co.morris.nj.us/apis/spatial-api',

  // API Keys
  nearmapKey: 'MWFkNGYyOWYtN2JkNS00ZWIzLWFlNDctNTdiODU5ZWE0ZGM0',
};
